In [76]:
from arch.bootstrap import StationaryBootstrap, IIDBootstrap, CircularBlockBootstrap, MovingBlockBootstrap, IndependentSamplesBootstrap
from modified_arch_bootstrap import *

from numpy.random import standard_normal
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime

### #1

In [77]:
z = np.arange(10)
bs = CircularBlockBootstrap(5, z=z)

for a, b in bs.bootstrap(3):
    print(b['z'])


[7 8 9 0 1 4 5 6 7 8]
[8 9 0 1 2 2 3 4 5 6]
[1 2 3 4 5 1 2 3 4 5]


### #2

In [78]:
samples = 30
z = np.arange(100)
bs = CircularBlockBootstrap(5, z=z)

for a, b in bs.bootstrap(1):
    print(b['z'][:samples])

[78 79 80 81 82 61 62 63 64 65 36 37 38 39 40 85 86 87 88 89  4  5  6  7
  8 90 91 92 93 94]


### #3

In [79]:
samples = 30
z = np.arange(100)
bs = CircularBlockBootstrapM(30, 5, z=z)

for a, b in bs.bootstrap(3):
    print(b['z'])

[11 12 13 14 15  4  5  6  7  8 18 19 20 21 22 22 23 24 25 26 23 24 25 26
 27 17 18 19 20 21]
[11 12 13 14 15  4  5  6  7  8 20 21 22 23 24 26 27 28 29  0  7  8  9 10
 11 28 29  0  1  2]
[16 17 18 19 20 20 21 22 23 24 22 23 24 25 26 27 28 29  0  1 20 21 22 23
 24 21 22 23 24 25]
